### ISSUE TITLE
Hackagotchi got deleted

### ISSUE THREAD

**Issue by nzeng8** [hackagotchi/hackagotchi#101]
I'm not sure if this is related to #85 or not, since this was recently fixed, but now I only have one gempheus instead of two D:

**Comment by nzeng8** [comment]
The gempheus appears to be in the database but does not show up on slack

**Comment by Muirrum** [comment]
If I had to guess it's related to the slack API limitation on JSON object size

**Comment by saharshy29** [comment]
What do you mean that it got deleted? It seems fine to me.

**Comment by Muirrum** [comment]
Nick is referring to the actual 'gotchi that are in-game resources, not the slack app itself

**Comment by lukec11** [comment]
Duplicate of #50
