### ISSUE TITLE
Items disappearing when hackstead is too big

### ISSUE THREAD

**Issue by nzeng8** [hackagotchi/hackagotchi#110]
I think this is related to #50. Might also be related to #101. Not sure if the items are disappearing from slack, or from the actual database.

**Comment by hkatzdev** [comment]
Not sure if it is a slack API bug. They do not disappear from the database, but if it was a slack API bug I would assume it would return invalid blocks. Additionally I do not believe my plants were relieving ticks when they disappeared. Either way this is a dupe of #50 so unless there is any additional information I believe this should be closed.

**Comment by lukec11** [comment]
Closing as a duplicate of #50 .
