### ISSUE TITLE
Hackstead not appearing

### ISSUE THREAD

**Issue by wei2gao** [hackagotchi/hackagotchi#116]
My hackstead is flickering between existing and not existing (it shows the Monopolize on Adorableness? message). I think my hackstead has just recently become large enough to cause this issue. I tried transferring 20 warp powder to an alt (Robespierre) but this did not fix the issue.

**Comment by wei2gao** [comment]
The problem appears to have disappeared on its own.

**Comment by hkatzdev** [comment]
For future reference this is a duplicate of #47
