### ISSUE TITLE
Aloe Avanta EGG!

### ISSUE THREAD

**Issue by tanishq-soni** [hackagotchi/hackagotchi#129]
Its not an issue, its a suggestion for hackagotchi!
you can introduce an rare egg "aloe avanta egg" which can be craft by the 5 pieces of eggs! and the pieces will be be getting from hatching normal eggs and to craft egg we need an aloe avanta plant of max level in which with help of that 5 pieces we can craft "aloe avanta egg" which gives lots of powders and stuffs from hatching!
I have some designs of egg which i will attach a link.

Egg 1: [https://hackclub.slack.com/files/U015MMJ6XKP/F017AP9QP7X/image_from_ios.png](url)
Egg 2: [https://hackclub.slack.com/files/U015MMJ6XKP/F0175CRLKNJ/image_from_ios.png](url)
Egg part: [https://hackclub.slack.com/files/U015MMJ6XKP/F017QP7627K/image_from_ios.png](url)

Hope you will like my Idea!

**Comment by tanishq-soni** [comment]
> Its not an issue, its a suggestion for hackagotchi!
> you can introduce an rare egg which can be craft by the 5 pieces of eggs! and the pieces will be be getting from hatching normal eggs and to craft egg we need an aloe avanta plant of max level in which with help of that 5 pieces we can create which gives lots of powders and stuffs from hatching!
> I have some designs of egg which i will attach a link.
> 
> Egg 1: [https://hackclub.slack.com/files/U015MMJ6XKP/F017AP9QP7X/image_from_ios.png](url)
> Egg 2: [https://hackclub.slack.com/files/U015MMJ6XKP/F0175CRLKNJ/image_from_ios.png](url)
> Egg part: [https://hackclub.slack.com/files/U015MMJ6XKP/F017QP7627K/image_from_ios.png](url)
> 
> Hope you will like my Idea!

**Comment by nzeng8** [comment]
Sorry but adding an Aloe Avanta Egg would break some things in-game in terms of a game design perspective. It kinda messes up the balancing, and we've thought of different ways to make Aloe Avanta more interesting.

**Comment by tanishq-soni** [comment]
Okay no problem!
But in future i want to see that.
