### ISSUE TITLE
Log all hackagotchi transactions in #hackagotchi-banker-chat

### ISSUE THREAD

**Issue by nzeng8** [hackagotchi/hackagotchi#140]
This will allow us to accurately determine how many items are lost when db errors occur from large `/hgive` transfers.

**Comment by hugomimihu** [comment]
Hi, I lost around 800-1200 in cyl crystal in transferring large amounts.

**Comment by lukec11** [comment]
@hugomimihu : This is a symptom of #82, not #140. You can report your experience there, but we're aware of the bug and are working on it.

**Comment by hugomimihu** [comment]
Sorry my bad I'll delete!

**Comment by lukec11** [comment]
@nzeng8 : This isn't a realistic expectation. Not only will a lot of transfers occur from outside of slack but more importantly, we would probably be rate limited by the amount of (db) transactions which it would be forced to log. the `debug!` macro (or an theoretical `info!` macro) is a more realistic for this to be logged, but even that is really unnecessary.

 The correct solution is to fix #82 which this does not, so I'm going to close.
