### ISSUE TITLE
Instant Crafting

### ISSUE THREAD

**Issue by rfblock** [hackagotchi/hackagotchi#15]
Attempted to craft a cyscrystal. Crafted instantly. I do not know how to reproduce this effect

**Comment by hkatzdev** [comment]
Wonder if this is related to #16 - maybe the data got messed up somehow and changed a time value to 0?

**Comment by Ninja9000** [comment]
This might have happened if you're Hackstead updated weirdly: started craft after long period of inactivity before ticks load.
