### ISSUE TITLE
Incorporate Market Into App Home

### ISSUE THREAD

**Issue by ageor0114** [hackagotchi/hackagotchi#17]
Adding the `/hackmarket` GUI to the Home tab of the hackagotchi app would be extremely convenient. This would make viewing the market much more accessible in realtime, instead of having to query the command. It would make people less likely to bloat **#hackmarket** and **hackstead** with `/hackmarket` b/c the market is just a single click away in the app. In terms of placement, right below the inventory should be fine. It's a small change but would make the user experience much more fluid.

**Comment by lukec11** [comment]
This would be difficult to do, due to slack's size limit for app homes (similar to the issue that caused #27).

**Comment by nzeng8** [comment]
We're kinda removing the market anyways, it was an unintentional feature to the game

**Comment by lukec11** [comment]
Yup, I'm actually just going to close this for now.
