### ISSUE TITLE
HackMarket becomes too Large to Send

### ISSUE THREAD

**Issue by hkatzdev** [hackagotchi/hackagotchi#27]
When enough items are listed, Hack Market exceeds the slack size limit, causing an invalid blocks error.

**Comment by hkatzdev** [comment]
For reference, slack has a 16k size limit and a 50 block limit. https://api.slack.com/reference/block-kit/blocks https://api.slack.com/docs/rate-limits

**Comment by ageor0114** [comment]
It's not a perfect solution, but Issue #17 would double the block limit from 50 to 100.
