### ISSUE TITLE
Crafting can be done from "read-only" snapshot

### ISSUE THREAD

**Issue by lukec11** [hackagotchi/hackagotchi#28]
Steps to reproduce: 
1. Run `/hackstead` command
2. Select `Crafting` button
3. Select an item to craft
4. Click on "your hackstead" (or go to the hackagotchi's app home directly)

I have tested this on my own hackstead - have not tested it on anyone else's.

**Comment by cedric-h** [comment]
wish I had a PR to point to here but I don't, but this is fixed.
