### ISSUE TITLE
Incorrect Crafting Time

### ISSUE THREAD

**Issue by ageor0114** [hackagotchi/hackagotchi#34]
Crafting bressence on my plant takes 10 minutes. The confirmation window inaccurately states 20 minutes:

<img width="629" alt="inaccuratecrafttime" src="https://user-images.githubusercontent.com/29669926/82488102-59830580-9aad-11ea-8e02-b9b79518b1fc.PNG">

**Comment by Ninja9000** [comment]
This is because higher level plants have faster crafting speeds, as it increases with yield speed boosts.

**Comment by cedric-h** [comment]
#39
