### ISSUE TITLE
Tax charge for reselling items

### ISSUE THREAD

**Issue by omgandhi** [hackagotchi/hackagotchi#35]
If I try to sell an item that's I have already put for sale on the hackmarket, even though the item doesn't go on sale again, I still get charged the tax. 

Specs:
- this happened when selling Bressence
- tax charge was 1gp

**Comment by Ninja9000** [comment]
Actually, as a dev with access to the banker logs, I can confidently say that you are refunded an invoice for items that were already on sale.

**Comment by cedric-h** [comment]
I think the bug here is just our failure to notify the user

**Comment by cedric-h** [comment]
#38
