### ISSUE TITLE
"Give" button returns no response

### ISSUE THREAD

**Issue by lukec11** [hackagotchi/hackagotchi#36]
While the "Give" button should theoretically redirect to a new modal, it instead returns no response - While there is no error or :warning: symbol shown, the problem persists.

Initial report was [here](https://hackclub.slack.com/archives/C012J554P8T/p1590086599050100).

**Comment by cedric-h** [comment]
this is because of me testing in production while implementing #37 lol

**Comment by cedric-h** [comment]
(should be fixed now ofc)
