### ISSUE TITLE
Add an Open Source License

### ISSUE THREAD

**Issue by hkatzdev** [hackagotchi/hackagotchi#61]
Please add an open source license. For a game this fully featured I recommend a GPL license, either 2 or 3 depending on your preferences.

**Comment by cedric-h** [comment]
ew no, MIT/Apache 2.0

**Comment by cedric-h** [comment]
that being said, the assets/config files should be property of hackagotchi team

**Comment by hkatzdev** [comment]
Maybe BSD 3 clause then? Is clearing on source code - from https://opensource.stackexchange.com/a/9545 - `In MIT license, the word "Software" with a capital "S" is explicitly defined as being "this software and associated documentation files". In the BSD licenses, they talk about "source code and binary form", no mention of documentation.` 

For documentation, art, assets, config, etc perhaps a CC BY-NC-ND 4.0 license? https://creativecommons.org/licenses/by-nc-nd/4.0/

**Comment by hkatzdev** [comment]
Also why the hate on GPL lol, I mean I usually use MIT but at the same time this is a pretty big project you put a lot of work into.

**Comment by hkatzdev** [comment]
Also another thing to keep in mind is that, since this is a public project on Github, people already have the right to fork the repo and link to assets in the repo according to https://help.github.com/en/github/site-policy/github-terms-of-service#5-license-grant-to-other-users. May as well set a proper license.

**Comment by hkatzdev** [comment]
So idk the licensing situation rn, I still recommend BSD 3 Clause for the open source parts based on your comments. cc @cedric-h @Muirrum since you are both working on the licensing part.

**Comment by cedric-h** [comment]
If we do use BSD -- and I'm starting to think that's a good idea -- we should make a note in the README, like, "this is basically MIT or Apache 2.0 like you're used to, except our configuration files and artwork _aren't_ free as in freedom.

**Comment by Muirrum** [comment]
Github will summarize the license at the top of the file (as long as we
use the template for BSD 3-Clause).

I agree with using the BSD license. What are we licensing assets under?
