### ISSUE TITLE
Incorrect notifications

### ISSUE THREAD

**Issue by nzeng8** [hackagotchi/hackagotchi#87]
![Screen Shot 2020-06-30 at 10 43 30 PM](https://user-images.githubusercontent.com/53419893/86207324-28253d00-bb23-11ea-8648-10566d6d725d.png)

As you can see in my notifications center, it says that my plant has leveled up, yet in reality it was the completion of a craft by the plant.

**Comment by lukec11** [comment]
Whoops, my bad - I labeled this notification incorrectly. I'll fix tomorrow :+1:
